### Step 1. Retrieve and save a JWT token.
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "jetbrains",
  "password": "foobar"
}

> {% client.global.set("auth_token", response.body.token); %}

### Step 2. Use a JWT token to authorize.
GET http://localhost:8080/hello
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8080/users
Content-Type: application/json

###
POST localhost:8080/users
Content-Type: application/json

{
  "userId": 0,
  "name": "John Doe Moe",
  "userType": "REGISTERED",
  "email": "a2.a@a.com",
  "link": "hello.world1",
  "aboutMe": "Hello23",
  "content": [
    {
      "contentId": 1,
      "text": "one two three",
      "createdAt" : "2010-06-01T22:19:44"
    }
  ]
}

###
PUT localhost:8080/users/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "userId": 1,
  "name": "John Doe",
  "userType": "REGISTERED",
  "email": "xxxxx.a@a.com",
  "link": "hello.world1",
  "aboutMe": "Hello23",
  "content": [
    {
      "contentId": 1,
      "text": "one two three",
      "createdAt" : "2010-06-01T22:19:44"
    }
  ]
}

###
@userId =1
GET http://localhost:8080/users/{{userId}}
Content-Type: application/json

####
@userIdToDelete =0
DELETE http://localhost:8080/users/{{userIdToDelete}}
